feature: fix folder structure
magang-mknows/mknows-fe pull request #170
Opened 2023-05-08 15:22 UTC by fauzannmw

2023-05-08 17:13 UTC, bangmar requested changes
cek jan

2023-05-08 17:13 UTC, bangmar commented on apps/kg/pages/rencana-studi/index.tsx
> +import StudyPlan from '../../modules/study-plan/choice-faculty';
import nya jangan gini atuh, samain sama kaya import { BaseLayout } atau { BreadCrumb }

2023-05-08 17:13 UTC, bangmar commented on apps/kg/pages/profile/reset-password/index.tsx
>  import ResetPassword from '../../../modules/profile/section/reset-password/ResetPassword';
ini juga samain

2023-05-08 17:13 UTC, bangmar commented on apps/kg/modules/study-plan/choice-faculty/index.tsx
>  const StudyPlan: FC = (): ReactElement => {
export const StudyPlan: FC = (): ReactElement => { 
   ... 
}

soalnya di index.ts diluar udh kamu export * from "./choice-faculty" 


cek yang lain juga siapa tau masih ada yg gini

2023-05-09 00:24 UTC, fauzannmw commented on apps/kg/modules/study-plan/choice-faculty/index.tsx
>  const StudyPlan: FC = (): ReactElement => {
oke mar

2023-05-09 04:50 UTC, bangmar commented on apps/kg/modules/study-plan/choice-faculty/index.tsx
>  const StudyPlan: FC = (): ReactElement => {
ngapain di branch baru jan awkowkowk lngsng update branch ini aja tadinya

2023-05-09 06:14 UTC, maulanasdqn approved these changes

2023-05-09 06:14 UTC, merged