integration api administration
magang-mknows/mknows-fe pull request #268
Opened 2023-05-14 06:52 UTC by GarnesPratama

- view value from api administration
- integration api administration done

2023-05-14 11:47 UTC, bangmar commented on apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
>      employee_id_number: z.string().min(1, { message: ' NIP harus diisi' }),
disini validasi string, di textfield nya juga string, brarrti ga number juga valid? harusnya number doang ga si? mungkin di textfield nya diganti type number nes? atau emang bisa string dan number nantinya untuk nip ini?

2023-05-14 11:49 UTC, bangmar commented on apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
>      employee_id_number: z.string().min(1, { message: ' NIP harus diisi' }),
btw knapa lxp nya gagal build?

2023-05-14 12:07 UTC, GarnesPratama commented on apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
>      employee_id_number: z.string().min(1, { message: ' NIP harus diisi' }),
Limit mungkin bang

2023-05-14 14:28 UTC, GarnesPratama commented on apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
>      employee_id_number: z.string().min(1, { message: ' NIP harus diisi' }),
udah diganti ya mar inputnya

2023-05-14 14:29 UTC, GarnesPratama commented on apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
>      employee_id_number: z.string().min(1, { message: ' NIP harus diisi' }),
untuk build mungkin kena limit soalnya aku build dr awal bisa dan test aman

2023-05-14 15:25 UTC, maulanasdqn requested changes

2023-05-14 15:25 UTC, maulanasdqn commented on apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
> +      company: data?.data.company,
jangan gini
coba liat apps/kg/modules/profile

2023-05-15 09:41 UTC, maulanasdqn requested changes
cek lagi

2023-05-15 09:41 UTC, maulanasdqn commented on apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
> +  const userData = data?.data;
ngapa di namain userData co kan ini bukan Update Profile

2023-05-15 09:41 UTC, maulanasdqn commented on apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
> +    userData == undefined
jangan lagi pake == dua pake ===

2023-05-15 09:57 UTC, maulanasdqn approved these changes

2023-05-15 09:57 UTC, merged