improvement : integrate my-training video module
magang-mknows/mknows-fe pull request #540
Opened 2023-06-08 04:10 UTC by GarnesPratama

- create types my-training video module
- create recoil my-training video module
- create custom hooks GET my-training video module
- integrate pages my-training video module

2023-06-08 05:06 UTC, bangmar commented on apps/lxp/modules/my-training-video-module/type.d.ts
> +export type params = {
bang kalo bisa namanya jangan params doang anjim awokwkk

2023-06-08 06:16 UTC, maulanasdqn requested changes
cek ce lagi

2023-06-08 06:16 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/type.d.ts
> +export type params = {
nah

2023-06-08 06:16 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/section/ListStudy.tsx
> +import { params } from "../type";
jangan params doang

2023-06-08 06:16 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/section/ListStudy.tsx
> +          {videoModule?.map((item: any, index: number) => {
jangan any

2023-06-08 06:16 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/section/ListStudy.tsx
> +          {docModule?.map((item: any, index: number) => {
jangan any, declare aja type nya

2023-06-09 04:32 UTC, maulanasdqn requested changes
lebih perhatikan lagi mengenai naming convention

2023-06-09 04:32 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/api.ts
> +import { paramsVideoModule } from "./type";
naming convention nya atuh jangan gini 

tapi gini TVideoModuleParams

2023-06-09 04:32 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/pop-up/send.tsx
> +      <h1 className="flex p-4 pt-2 rounded-md bg-[#F26800] text-white w-full text-[18px]">
ini bg-[#blabla] jagan gini, masukin ke tailwind config js

2023-06-09 04:32 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/pop-up/send.tsx
> +          className="bg-[#F26800] h-[32px] text-white lg:w-[115px] w-full rounded-md"
ini juga

2023-06-09 04:32 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/section/ContentSection.tsx
>      <div className="mx-6 md:mx-8 lg:px10 my-2  bg-[#FFFF] shadow-sm rounded-[8px]">
ini juga

2023-06-09 04:32 UTC, maulanasdqn commented on apps/lxp/modules/my-training-video-module/section/Description.tsx
> -      <h1 className="text-[18px] font-[600] text-[#171717]  h-269px ">{titleVideo}</h1>
ini juga color masukin ke tailwind config

2023-06-09 05:27 UTC, maulanasdqn approved these changes

2023-06-09 05:27 UTC, merged