improvement: spacing col on all tables cs, update download button on expandable row, and card cs moved to libs with name CardCS
magang-mknows/mknows-fe pull request #543
Opened 2023-06-08 07:02 UTC by mochilhamsyah17

2023-06-08 11:00 UTC, maulanasdqn requested changes
pokonya warna yang masih pake bg-[balblanla] declare dia di tailiwnd config

2023-06-08 11:00 UTC, maulanasdqn commented on apps/cs/src/modules/report/report-user/table.tsx
> +          className="flex flex-row my-2 py-[6px] px-2 mr-[16%] border-[#E5E5E5] border-[1px] rounded-md items-center space-x-1"
declare di tailwind config js warna  nya jangan gini atuh

2023-06-08 11:00 UTC, maulanasdqn commented on apps/cs/src/modules/request/check-result/index.tsx
>            <div className="flex flex-row gap gap-x-5 items-center border-b-[1px] border-solid w-full h-fit py-7 text-[#4AC1A2] font-bold text-base">
ini juga

2023-06-08 11:00 UTC, maulanasdqn commented on apps/cs/src/modules/request/check-result/index.tsx
>                          <div className="text-[#737373] ">(10/100)</div>
ini juga

2023-06-08 11:00 UTC, maulanasdqn commented on apps/cs/src/modules/request/check-result/index.tsx
>                  <div className="bg-[#D0E6F5] rounded-full w-fit p-1">
ini juga

2023-06-08 11:00 UTC, maulanasdqn commented on apps/cs/src/modules/request/check-result/table.tsx
>                  <div className="bg-[#D0E6F5] rounded-full w-fit p-1">
ini juga

2023-06-09 09:07 UTC, mochilhamsyah17 commented on apps/cs/src/modules/request/check-result/table.tsx
>                  <div className="bg-[#D0E6F5] rounded-full w-fit p-1">
dah semua ngab

2023-06-09 11:04 UTC, maulanasdqn approved these changes

2023-06-09 11:04 UTC, merged